# This workflow is managed by gh actions-lock.

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
jobs:
  bam:
    runs-on: ubuntu-slim
    steps:
      - run: exit 0
        if: false
