# This workflow is managed by gh actions-lock.

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
jobs:
  A:
    uses: $/.github/workflows/reusable.yml
  B:
    needs: [A]
    runs-on: ubuntu-slim
    if: cancelled()
    steps:
      - run: echo B
  delay:
    runs-on: ubuntu-slim
    if: cancelled()
    steps:
      - run: sleep 1
  cancel:
    needs: [delay]
    uses: $/.github/workflows/reusable.yml
