# This workflow is managed by gh actions-lock.

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
jobs:
  my-one:
    uses: $/.github/workflows/reusable.yml
  my-two:
    uses: $/.github/workflows/reusable.yml
  my-three:
    needs:
      - my-one
      - my-two
    runs-on: ubuntu-slim
    steps:
      - run: sleep 10; exit 1
