# This workflow is managed by gh actions-lock.

on:
  workflow_call:
concurrency:
    group: reusable
    cancel-in-progress: true
jobs:
  child-check:
    runs-on: ubuntu-slim
    steps:
      - run: sleep 10
  failure:
    runs-on: ubuntu-slim
    steps:
      - run: false
