# This workflow is managed by gh actions-lock.

on:
  workflow_call:
concurrency:
    group: reusable
    cancel-in-progress: true
jobs:
  hack:
    runs-on: ubuntu-slim
    steps:
      - uses: $/nonexistent
