on:
  workflow_dispatch:
jobs:
  first:
    runs-on: ubuntu-slim
    steps:
      - run: sleep 120
  second:
    if: (!cancelled())
    needs:
      - first
    runs-on: ubuntu-slim
    steps:
      - run: echo oi
