on:
  workflow_dispatch:
  push:
    branches: main
jobs:
  my-one:
    name: my
    runs-on: ubuntu-slim
    steps:
      - run: sleep 120
  my-two:
    name: my
    runs-on: ubuntu-slim
    steps:
      - run: sleep 120
