on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
jobs:
  my-one:
    name: my
    runs-on: ubuntu-slim
    steps:
      - run: exit 0
  my-two:
    name: my
    runs-on: ubuntu-slim
    steps:
      - run: sleep 10; exit 1
